-- Advanced Questions :

-- Q1. Retrieve the total number of books sold for each genre.

SELECT b.genre, SUM(o.quantity) as total_books_sold
FROM book as b 
JOIN orders as o
on b.book_id = o.book_id
GROUP BY b.genre;


-- Q2. Find the average price of books in the "Fantasy" genre.

SELECT AVG(price) AS average_price
FROM book
WHERE genre = 'Fantasy';



-- Q3. List customers who have placed at least 2 orders.

SELECT c.customer_id, c.name, COUNT(o.order_id) as total_orders 
FROM customers as c
join orders as o
on c.customer_id = o.customer_id 
GROUP BY c.customer_id, c.name
HAVING COUNT(o.order_id) >= 2;


-- Q4. Find the total revenue generated by each book.

SELECT b.book_id, SUM(o.quantity*b.price) as Total_revenue, b.title 
FROM orders as o
JOIN book as b
on o.book_id = b.book_id
GROUP BY b.book_id, b.title ;


-- Q5. Find the most frequently ordered book.

SELECT b.book_id,
       b.title AS frequently_ordered_book,
       COUNT(o.order_id) AS total_order
FROM book AS b
JOIN orders AS o
ON b.book_id = o.book_id
GROUP BY b.book_id, b.title
ORDER BY total_order DESC
LIMIT 1;


-- Q6. Find customers who have never placed an order.

SELECT c.name, o.customer_id
from customers as c
left join orders as o
on c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Q7. Show the top 3 most expensive books of 'Fantasy' Genre

SELECT title as Expensive_books , genre, price FROM book 
WHERE genre ='Fantasy'
ORDER BY price DESC LIMIT 3;

-- Q8. Retrieve the total quantity of books sold by each author

SELECT b.author, SUM(o.quantity) as Total_quantity
from book as b
join orders as o
on b.book_id = o.book_id
GROUP BY  b.author;


-- Q9. List the cities where customers who spent over $30 are located 

SELECT c.city , o.total_amount
FROM customers c
join orders o
on c.customer_id = o.customer_id
where o.total_amount > 30
;


-- Q10. Find the customer who spent the most on orders

SELECT c.customer_id, c.name, sum(o.total_amount) 
FROM  customers c
JOIN orders o
on c.customer_id = o.customer_id
group by c.customer_id, c.name
order by sum(o.total_amount) DESC
limit 1
;


-- Q11.Calculate the stock remaining after fulfilling all orders

SELECT b.book_id, b.title,  b.stock,
    COALESCE(SUM(o.quantity), 0) AS total_sold,
    b.stock - COALESCE(SUM(o.quantity), 0) AS remaining_stock
FROM book b
LEFT JOIN orders o
ON b.book_id = o.book_id
GROUP BY b.book_id, b.title, b.stock;
